import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

const currentDir = dirname(fileURLToPath(import.meta.url))
const chatPanelSource = readFileSync(resolve(currentDir, '../ChatPanel.vue'), 'utf-8')
const broadcastPlanSource = readFileSync(resolve(currentDir, '../../../views/broadcast-plan/create.vue'), 'utf-8')
const orchestrationHookSource = readFileSync(resolve(currentDir, '../../../views/broadcast-plan/useBroadcastPlanOrchestration.ts'), 'utf-8')

describe('ChatPanel quick actions', () => {
  it('exposes long-flow scheduling as explicit non-atomic quick actions', () => {
    const quickActionsBlock = chatPanelSource.match(/const quickActions[\s\S]*?= \[[\s\S]*?\n\]/)?.[0] ?? ''

    expect(quickActionsBlock).toContain('新建电视播单')
    expect(quickActionsBlock).toContain('新建轮播单')
    expect(quickActionsBlock).toContain('内容匹配优先')
    expect(quickActionsBlock).toContain('收视率优先')
    expect(quickActionsBlock).toContain('热播优先')
    expect(quickActionsBlock).toContain('连续剧检查')
    expect(quickActionsBlock).toContain('SEED_TV_SEQUENCE_CONTEXT_PROMPT')
    expect(quickActionsBlock).toContain('顺播倒序')
    expect(quickActionsBlock).toContain('08:00 插入纵有疾风起第2集')
    expect(quickActionsBlock).toContain('插入节目')
    expect(quickActionsBlock).toContain('插入短片')
    expect(quickActionsBlock).toContain('0点插入城市形象春日花路短片')
    expect(quickActionsBlock).toContain("{ label: '插入短片', prompt: '0点插入城市形象春日花路短片', playlistTypes: ['rotation'] }")
    expect(quickActionsBlock).toContain('替换节目')
    expect(quickActionsBlock).toContain('删除节目')
    expect(quickActionsBlock).toContain('后移节目')
    expect(quickActionsBlock).toContain('前移节目')
    expect(quickActionsBlock).toContain('查询节目')
    expect(quickActionsBlock).toContain('9点是什么节目')
    expect(quickActionsBlock).toContain('按内容匹配优先')
    expect(quickActionsBlock).toContain('按收视率优先')
    expect(quickActionsBlock).toContain('按热播优先')
    expect(quickActionsBlock).toContain('把9点的节目向后移动1小时')
    expect(quickActionsBlock).toContain('把10点的节目向前移动1小时')
    expect(quickActionsBlock).not.toContain('把22点的节目向后移动1小时')
    expect(quickActionsBlock).toContain('全天编排')
    expect(quickActionsBlock).toContain('帮我全天编排')
    expect(quickActionsBlock).toContain('补齐空窗')
    expect(quickActionsBlock).toContain('补齐当前所有空窗')
    expect(quickActionsBlock).not.toContain('缺时间插入')
    expect(quickActionsBlock).not.toContain("prompt: '插入看东方'")
    expect(chatPanelSource).toContain('const visibleQuickActions = computed')
    expect(chatPanelSource).toContain('action.playlistTypes.includes(activePlaylistType.value)')
    expect(chatPanelSource).toContain(':disabled="loading"')
    expect(chatPanelSource).toContain("emit('seedTvSequenceContextRequested')")
    expect(chatPanelSource).toContain('后续插入或替换同系列节目时')
    expect(broadcastPlanSource).toContain('@seed-tv-sequence-context-requested="handleSeedTvSequenceContext"')
    expect(broadcastPlanSource).toContain('persistCurrentPlaylistDocument()')
  })

  it('syncs runtime playlist state details back to the parent page', () => {
    expect(chatPanelSource).toContain('const applyPlaylistStateFromDetails')
    expect(chatPanelSource).toContain('details?.playlistState')
    expect(chatPanelSource).toContain('playlistId: playlistState.playlistId')
    expect(chatPanelSource).toContain('channelName: activePlaylistType.value === \'tv\' ? playlistState.channelName : undefined')
    expect(chatPanelSource).toContain('date: activePlaylistType.value === \'tv\' ? playlistState.date : undefined')
    expect(chatPanelSource).toContain('activePlaylistType.value = playlistState.playlistType')
    expect(chatPanelSource).toContain("emit('playlistStateChanged'")
    expect(chatPanelSource).toContain("rotationStrategy: activePlaylistType.value === 'rotation' ? activeRotationStrategy.value : undefined")
    expect(chatPanelSource).toContain('playlistType: activePlaylistType.value')
    expect(chatPanelSource).toContain("rotationStrategy: activePlaylistType.value === 'rotation' ? activeRotationStrategy.value : undefined")
    expect(chatPanelSource).toContain('activeRotationDurationSeconds.value = activePlaylistType.value === \'rotation\' && typeof playlistState.rotationDurationSeconds === \'number\'')
    expect(chatPanelSource).toContain('rotationDurationSeconds: activePlaylistType.value === \'rotation\' ? activeRotationDurationSeconds.value ?? undefined : undefined')
  })

  it('opens playlist file cards by stable playlist id', () => {
    expect(chatPanelSource).toContain('playlistId?: string')
    expect(chatPanelSource).toContain('playlistId: card.playlistId')
    expect(chatPanelSource).toContain('explanation: feedback.explanation || details')
    expect(broadcastPlanSource).toContain('type PlaylistDocumentState')
    expect(broadcastPlanSource).toContain('const playlistDocuments')
    expect(broadcastPlanSource).toContain('const openPlaylistDocument')
    expect(broadcastPlanSource).toContain('payload.playlistId')
    expect(broadcastPlanSource).toContain('playlistDocuments.value.find((item) => item.id === payload.playlistId)')
  })

  it('persists the active playlist document after foreground Agent writeback', () => {
    expect(broadcastPlanSource).toContain('persistCurrentPlaylistDocument,')
    expect(orchestrationHookSource).toContain('persistCurrentPlaylistDocument: () => void')
    expect(orchestrationHookSource).toContain('options.applyRuntimeScheduleItems(items)')
    expect(orchestrationHookSource).toContain('options.persistCurrentPlaylistDocument()')
    expect(orchestrationHookSource.indexOf('options.applyRuntimeScheduleItems(items)')).toBeLessThan(
      orchestrationHookSource.indexOf('options.persistCurrentPlaylistDocument()'),
    )
  })

  it('renders playlist file cards from snapshot metadata rather than current page props', () => {
    expect(chatPanelSource).toContain('playlistState.channelName.trim()')
    expect(chatPanelSource).toContain('playlistState.date.trim()')
    expect(chatPanelSource).toContain('title: `${channelName}电视播单`')
    expect(chatPanelSource).toContain('meta: `${date} · ${channelName} · 编排内容`')
    expect(broadcastPlanSource).toContain('channelName?: string')
    expect(broadcastPlanSource).toContain('date?: string')
    expect(broadcastPlanSource).toContain('scheduleForm.value.channelName = document.channelName')
    expect(broadcastPlanSource).toContain('scheduleForm.value.date = document.date')
  })

  it('keeps the AI conversation as a permanent primary entry', () => {
    expect(broadcastPlanSource).toContain('<div class="content-wrapper with-ai-sidebar">')
    expect(broadcastPlanSource).toContain('<div class="ai-sidebar">')
    expect(broadcastPlanSource).not.toContain('aiSidebarVisible = false')
    expect(broadcastPlanSource).not.toContain('class="ai-sidebar-close"')
    expect(broadcastPlanSource).toContain('class="assistant-workspace-close"')
  })

  it('keeps layout draft viewing out of the foreground conversation and playlist workspace', () => {
    expect(chatPanelSource).not.toContain('v-if="pendingLayoutDraft" class="pending-command-panel layout-draft-panel"')
    expect(chatPanelSource).not.toContain('class="layout-upload-status"')
    expect(chatPanelSource).toContain('const containsForegroundDraftPayload')
    expect(chatPanelSource).toContain('hiddenFromThread?: boolean')
    expect(chatPanelSource).toContain('const hiddenFromThread = input.hiddenFromThread')
    expect(chatPanelSource).toContain('&& containsForegroundDraftPayload(input)')
    expect(chatPanelSource).toContain('&& !shouldKeepDraftBlockingInputVisible(input)')
    expect(chatPanelSource).toContain('&& !shouldKeepReadOnlyAnalysisInputVisible(input)')
    expect(chatPanelSource).toContain('messages.value.filter((message) => !message.hiddenFromThread && !isForegroundLayoutDraftMessage(message))')
    expect(chatPanelSource).toContain('const sanitizeForegroundDraftText')
    expect(chatPanelSource).toContain('const sanitizeForegroundDraftPayload')
    expect(chatPanelSource).toContain('const sanitizeAssistantMessageInput')
    expect(chatPanelSource).toContain('const isForegroundDraftPayloadKey')
    expect(chatPanelSource).toContain('value.includes(\'编排参考\')')
    expect(chatPanelSource).toContain('isForegroundDraftPayloadKey(key)')
    expect(chatPanelSource).toContain('sanitizeForegroundDraftPayload(input.explanation)')
    expect(chatPanelSource).toContain('const getVisibleMessageDetails')
    expect(chatPanelSource).toContain('buildDetailsSummary(getVisibleMessageDetails(message), message.processType)')
    expect(chatPanelSource).toContain('v-if="getDetailsSummaryItems(message).length > 0 || getVisibleMessageDetails(message)"')
    expect(chatPanelSource).not.toContain('v-if="getDetailsSummaryItems(message).length > 0 || message.explanation?.details"')
    expect(chatPanelSource).toContain('Boolean(getVisibleMessageDetails(message))')
    expect(chatPanelSource).toContain('normalizedKey === \'layoutdraft\'')
    expect(chatPanelSource).toContain('normalizedKey === \'draftid\'')
    expect(chatPanelSource).toContain('normalizedKey === \'layoutsource\'')
    expect(chatPanelSource).toContain('formatStructuredDetails(sanitizeForegroundDraftPayload(details), formatDisplayTime)')
    expect(chatPanelSource).toContain('const isForegroundLongFlowDetails')
    expect(chatPanelSource).toContain('isOrchestrationOverviewDetails(details)')
    expect(chatPanelSource).toContain('containsForegroundDraftPayload(message.explanation?.explanation)')
    expect(chatPanelSource).toContain("if (message.role === 'user') return false")
    expect(chatPanelSource).not.toContain("if (foregroundLayoutDraftEnabled || message.role === 'user') return false")
    expect(chatPanelSource).not.toContain('当前版面参考</span>')
    expect(broadcastPlanSource).not.toContain('const foregroundLayoutDraftWorkspaceEnabled = false')
    expect(broadcastPlanSource).toContain('const showLayoutDraftWorkspace = computed(() => (')
    expect(broadcastPlanSource).toContain('playlistType.value === \'tv\'')
    expect(broadcastPlanSource).toContain('playlistType.value === \'rotation\' && Boolean(currentLayoutDraft.value)')
    expect(broadcastPlanSource).toContain('const showLayoutDraftTab = computed(() => showLayoutDraftWorkspace.value)')
    expect(broadcastPlanSource).toContain('const currentPlaylistWorkspaceKicker = computed(() => {')
    expect(broadcastPlanSource).toContain('class="playlist-workspace-tabs" :class="{ \'is-disabled\': playlistType === \'none\' }"')
    expect(broadcastPlanSource.indexOf('class="playlist-workspace-tabs"')).toBeLessThan(
      broadcastPlanSource.indexOf('class="playlist-workspace-title"'),
    )
    expect(broadcastPlanSource).toContain('justify-content: space-between;')
    expect(broadcastPlanSource).toContain('text-align: right;')
    expect(broadcastPlanSource).not.toContain('const showPlaylistWorkspaceTabs = computed(() => playlistType.value !== \'none\')')
    expect(broadcastPlanSource).not.toContain('v-if="showPlaylistWorkspaceTabs" class="playlist-workspace-tabs"')
    expect(broadcastPlanSource).toContain('v-if="showLayoutDraftTab"')
    expect(broadcastPlanSource).toContain(':disabled="!showLayoutDraftWorkspace"')
    expect(broadcastPlanSource).toContain('v-else-if="showLayoutDraftWorkspace && currentLayoutDraft" class="layout-draft-workspace"')
    expect(broadcastPlanSource).toContain('v-else-if="showLayoutDraftWorkspace" class="layout-draft-workspace is-empty"')
    expect(broadcastPlanSource).toContain('class="layout-draft-workspace"')
    expect(broadcastPlanSource).not.toContain('v-if="currentLayoutDraftFeasibility"\n                type="primary"')
    expect(broadcastPlanSource).not.toContain("currentLayoutDraftFeasibility.ok ? 'success' : 'primary'")
    expect(broadcastPlanSource).not.toContain('class="layout-draft-keyword-row"')
    expect(broadcastPlanSource).not.toContain("matchedCount > 0")
    expect(broadcastPlanSource).not.toContain('matchedCandidateCount')
    expect(broadcastPlanSource).not.toContain('候选 ${matchedCount}')
    expect(broadcastPlanSource).toContain("statusText")
    expect(broadcastPlanSource).toContain('v-if="segment.intent"')
    expect(broadcastPlanSource).toContain('formatLayoutDraftSegmentLabel(column')
    expect(broadcastPlanSource).not.toContain('return `栏目=${label}`')
    expect(broadcastPlanSource).not.toContain('return `节目=${label}`')
    expect(broadcastPlanSource).not.toContain('行内只展示可由草案提供的时段与栏目/节目名称')
    expect(broadcastPlanSource).not.toContain('正式编排时按栏目或同名节目匹配节目库')
    expect(broadcastPlanSource).not.toContain('正式编排时按历史进度续播')
    expect(broadcastPlanSource).not.toContain('正式编排时从同栏目候选中选取可用节目')
    expect(broadcastPlanSource).not.toContain("'参考'")
    expect(broadcastPlanSource).not.toContain('class="layout-draft-empty"')
    expect(broadcastPlanSource).not.toContain('还没有版面草案')
  })

  it('describes rotation playlists as duration based instead of concrete date or time ranges', () => {
    expect(chatPanelSource).toContain('const durationText = rotationDurationSeconds')
    expect(chatPanelSource).toContain('总时长 ${formatPlaylistDurationText(rotationDurationSeconds)}')
    expect(chatPanelSource).toContain("'待确定总时长'")
    expect(chatPanelSource).toContain('getRotationStrategyLabel(rotationStrategy)')
    expect(chatPanelSource).not.toContain('00:00:00 至 ${formatPlaylistClockText(rotationDurationSeconds)}')
    expect(broadcastPlanSource).toContain("const timelineStartHeaderLabel = computed(() => playlistType.value === 'rotation' ? '起始位置' : '起始时间')")
    expect(broadcastPlanSource).toContain("const timelineEndHeaderLabel = computed(() => playlistType.value === 'rotation' ? '结束位置' : '结束时间')")
    expect(broadcastPlanSource).toContain('总时长 ${formatDurationScopeText(rotationTargetDurationSeconds.value)}')
    expect(broadcastPlanSource).toContain("'待确定总时长'")
    expect(broadcastPlanSource).toContain("() => playlistType.value === 'rotation'")
    expect(broadcastPlanSource).toContain('? rotationDurationScopeText.value')
    expect(broadcastPlanSource).not.toContain('00:00:00 至 ${secondsToClockText(rotationTargetDurationSeconds.value)}')
    expect(broadcastPlanSource).toContain('layoutDraft: currentLayoutDraft.value')
    expect(broadcastPlanSource).toContain('document.layoutDraft ?? resolveCurrentTvLayoutDraft()')
    expect(broadcastPlanSource).toContain(': document.layoutDraft ?? null')
  })

  it('shows the active playlist as a compact assistant workspace instead of helper copy', () => {
    expect(broadcastPlanSource).toContain('class="assistant-workspace-chip"')
    expect(broadcastPlanSource).toContain('正在与${label}交互')
    expect(broadcastPlanSource).toContain('handleCloseAssistantWorkspace')
    expect(broadcastPlanSource).toContain('退出当前工作区后')
    expect(broadcastPlanSource).toContain(':workspace-closed-notice="assistantWorkspaceClosedNotice"')
    expect(chatPanelSource).toContain('workspaceClosedNotice?: string')
    expect(chatPanelSource).toContain("processTypeLabel: '工作区'")
    expect(broadcastPlanSource).not.toContain('aiSidebarSubtitle')
    expect(broadcastPlanSource).not.toContain('class="ai-sidebar-subtitle"')
    expect(broadcastPlanSource).not.toContain('var(--el-color-success)')
  })

  it('formats rotation ranges as duration and relative position in the foreground chat', () => {
    expect(chatPanelSource).toContain('总时长${durationText}，0点起算')
    expect(chatPanelSource).toContain('相对位置 +${formatPlaylistDurationText(startSeconds)}，持续${durationText}')
    expect(chatPanelSource).toContain('\\d{1,2}:\\d{2}(?::\\d{2})?')
    expect(chatPanelSource).not.toContain('0点起算，持续${durationText}')
  })

  it('routes the real foreground conversation through the scheduling runtime directly', () => {
    expect(chatPanelSource).toContain('const runtimeFacade = getSchedulingAgentRuntimeFacade()')
    expect(chatPanelSource).toContain("from '@/services/runtime/schedulingAgentRuntimeFacade'")
    expect(chatPanelSource).not.toContain('getDemoRuntimeFacade')
    expect(chatPanelSource).toContain('const decision = await runtimeFacade.submitInstruction')
    expect(chatPanelSource).toContain('agentCoreEnabled: true')
    expect(chatPanelSource).toContain('const foregroundLayoutDraftEnabled = false')
    expect(chatPanelSource).toContain('layoutDraftEnabled: foregroundLayoutDraftRuntimeEnabled')
    expect(chatPanelSource).toContain('const currentLayoutDraft = foregroundLayoutDraftRuntimeEnabled')
    expect(chatPanelSource).toContain('const pendingReviewLifecycle = resolvePendingReviewLifecycle')
    expect(chatPanelSource).toContain('const foregroundContextPackage = buildForegroundAgentContextPackage')
    expect(chatPanelSource).toContain('foregroundContextPackage,')
    expect(chatPanelSource).toContain('runtimeFacade.executePendingCommand')
    expect(chatPanelSource).toContain('runtimeFacade.resolvePendingTargetSelection')
    expect(chatPanelSource).toContain('runtimeFacade.resolvePendingInsertRecommendation')
    expect(chatPanelSource).not.toContain('openClawBridge.submitInstruction')
    expect(chatPanelSource).not.toContain('getOpenClawBridge')
    expect(orchestrationHookSource).toContain('targetTimeRange?: { start: string; end: string }')
    expect(orchestrationHookSource).toContain('searchKeywords?: string[]')
    expect(orchestrationHookSource).toContain("import { resolveFormalOrchestrationSearchKeywords } from '@/services/retrievalConstraintCompiler'")
    expect(orchestrationHookSource).toContain('resolveFormalOrchestrationSearchKeywords(payload.userInput)')
    expect(orchestrationHookSource).toContain('...(searchKeywords?.length ? { searchKeywords } : {})')
    expect(orchestrationHookSource).toContain('const effectiveTargetTimeRange = payload.targetTimeRange ?? payload.layoutDraft?.coverage')
    expect(orchestrationHookSource).toContain('targetTimeRange?.start ??')
  })

  it('switches back to the schedule workspace when formal orchestration starts', () => {
    expect(broadcastPlanSource).toContain('activateScheduleWorkspace: () => {')
    expect(broadcastPlanSource).toContain("activeWorkspaceTab.value = 'schedule'")
    expect(orchestrationHookSource).toContain('activateScheduleWorkspace?: () => void')
    expect(orchestrationHookSource).toContain('options.activateScheduleWorkspace?.()')
    expect(orchestrationHookSource.indexOf('options.activateScheduleWorkspace?.()')).toBeLessThan(
      orchestrationHookSource.indexOf('await startOrchestrationRuntime('),
    )
  })

  it('passes the foreground layout draft from the playlist workspace into runtime context', () => {
    expect(broadcastPlanSource).toContain(':current-layout-draft="currentLayoutDraft"')
    expect(chatPanelSource).toContain('currentLayoutDraft?: LayoutDraft | null')
    expect(chatPanelSource).toContain('const foregroundLayoutDraftRuntimeEnabled = true')
    expect(chatPanelSource).toContain('props.currentLayoutDraft ?? pendingLayoutDraft.value')
    expect(chatPanelSource).toContain('layoutDraftEnabled: foregroundLayoutDraftRuntimeEnabled')
    expect(chatPanelSource).toContain('appendLayoutDraftWorkspaceFeedback')
    expect(chatPanelSource).not.toContain('layoutDraftEnabled: foregroundLayoutDraftEnabled')
  })

  it('does not use draft candidate precheck as a visible draft-commit blocker', () => {
    expect(chatPanelSource).not.toContain('const blockedSegments = layoutDraftFeasibility.value?.segments.filter')
    expect(chatPanelSource).not.toContain('当前草案有不可编排段落，请先调整。')
    expect(chatPanelSource).toContain("emit('orchestrateRequested', {")
    expect(chatPanelSource).toContain("userInput: '按当前版面开始编排'")
    expect(chatPanelSource).toContain("decision.feedback.content || '左侧版面已更新，可以继续微调或确认进入编排；正式播单还没有开始编排。'")
  })

  it('reports failed formal orchestration gaps as manual follow-up instead of completion', () => {
    expect(chatPanelSource).toContain('const unresolvedGapCount = pendingGapCount + failedGapCount')
    expect(chatPanelSource).toContain("unresolvedGapCount > 0 ? '自动编排阶段已结束' : '全天编排已完成'")
    expect(chatPanelSource).toContain('仍有 ${unresolvedGapCount} 个空窗待人工确认')
  })

  it('keeps layout draft upload visible and syncs uploaded drafts into the playlist workspace', () => {
    const draftUpdatedBlock = broadcastPlanSource.match(/const handleChatLayoutDraftUpdated = \([\s\S]*?\nconst handleCreatePlaylist/)?.[0] ?? ''

    expect(chatPanelSource).toContain('ref="layoutFileInput"')
    expect(chatPanelSource).not.toContain('v-if="false"\n        ref="layoutFileInput"')
    expect(chatPanelSource).toContain('title="上传版面草案"')
    expect(chatPanelSource).toContain('class="input-shell"')
    expect(chatPanelSource).toContain('class="input-icon-button"')
    expect(chatPanelSource).toContain('class="send-action-button"')
    expect(chatPanelSource).toContain('resolveForegroundLayoutDraft')
    expect(chatPanelSource).toContain('const uploadedDraft = resolveForegroundLayoutDraft')
    expect(chatPanelSource).toContain("if (activePlaylistType.value === 'none')")
    expect(chatPanelSource).toContain('playlistType: activePlaylistType.value')
    expect(chatPanelSource).toContain("emit('layoutDraftUpdated', {")
    expect(chatPanelSource).toContain('draft: uploadedDraft')
    expect(chatPanelSource).not.toContain('class="layout-upload-button"')
    expect(draftUpdatedBlock).toContain('persistCurrentPlaylistDocument()')
    expect(broadcastPlanSource).toContain('const isSwitchingPlaylistType = payload.playlistType !== playlistType.value')
    expect(broadcastPlanSource).toContain("payload.playlistType === 'rotation' && (isNewPlaylistDocument || isSwitchingPlaylistType)")
    expect(broadcastPlanSource).not.toContain("if (payload.playlistType === 'rotation') {\n    currentLayoutDraft.value = null")
  })

  it('renders assistant process feedback separately from the main reply', () => {
    expect(chatPanelSource).toContain('getAssistantProcessLines(message).length > 0')
    expect(chatPanelSource).toContain('class="system-process-strip"')
    expect(chatPanelSource).toContain('assistantProcessSummary')
    expect(chatPanelSource).toContain('已检查当前播单：暂无草案。')
    expect(chatPanelSource).not.toContain('已根据当前时段、节目匹配度和风险提示完成这次处理。')
    expect(chatPanelSource).not.toContain('已结合当前空窗、候选匹配度和约束条件做出选择。')
    expect(chatPanelSource).toContain('已根据当前时段、节目线索和风险提示完成这次处理。')
    expect(chatPanelSource).toContain('已结合当前空窗、可用候选和约束条件做出选择。')
  })

  it('keeps natural-language draft switch feedback visible in the foreground chat', () => {
    expect(chatPanelSource).toContain('const visibleContent = /切换|上传版面|默认版面|频道版面/.test(feedback.content)')
    expect(chatPanelSource).toContain('const noticeMatch = feedback.content.match')
    expect(chatPanelSource).toContain('`${leadingNotice}\\n${visibleContent}`')
    expect(chatPanelSource).toContain("if (message.processTypeLabel === '版面更新' || message.processTypeLabel === '版面草案') return false")
    expect(chatPanelSource).toContain('isForegroundAgentMainReplyText(message.content)')
    expect(chatPanelSource).toContain("if (/^已切换到.+频道版面/.test(message.content)")
  })

  it('keeps rotation playlist creation independent from TV layout drafts', () => {
    const createPlaylistBlock = broadcastPlanSource.match(/const handleCreatePlaylist = \(type: Exclude<PlaylistType, 'none'>\) => \{[\s\S]*?\n\}/)?.[0] ?? ''
    const playlistStateChangedBlock = broadcastPlanSource.match(/const handlePlaylistStateChanged = \(payload: \{[\s\S]*?\nconst handlePlaylistFileOpenRequested/)?.[0] ?? ''

    expect(createPlaylistBlock).toContain("currentLayoutDraft.value = type === 'tv' ? resolveCurrentTvLayoutDraft() : null")
    expect(createPlaylistBlock).toContain("activeWorkspaceTab.value = type === 'tv' && currentLayoutDraft.value ? 'draft' : 'schedule'")
    expect(playlistStateChangedBlock).toContain("payload.playlistType === 'rotation' && (isNewPlaylistDocument || isSwitchingPlaylistType)")
    expect(playlistStateChangedBlock).toContain('currentLayoutDraft.value = null')
    expect(playlistStateChangedBlock).toContain('currentLayoutDraftFeasibility.value = null')
    expect(playlistStateChangedBlock).toContain("activeWorkspaceTab.value = payload.playlistType === 'tv' && currentLayoutDraft.value ? 'draft' : 'schedule'")
    expect(broadcastPlanSource).toContain("playlistType.value === 'rotation' && Boolean(currentLayoutDraft.value)")
    expect(chatPanelSource).toContain('clearPendingRuntimeTaskState({ clearLayoutDraft: playlistContextTransition.clearLayoutDraft })')
    expect(chatPanelSource).toContain('const clearPendingRuntimeTaskState = (options: { clearLayoutDraft?: boolean } = {}) =>')
    expect(chatPanelSource).toContain('if (options.clearLayoutDraft) {\n    clearPendingLayoutDraftState()')
  })

  it('keeps the broadcast-plan foreground page off the OpenClaw host bridge', () => {
    expect(broadcastPlanSource).not.toContain('getOpenClawHostAdapter')
    expect(broadcastPlanSource).not.toContain('openClawHostAdapter')
    expect(broadcastPlanSource).not.toContain('bigbiandan.openclaw')
  })

  it('shows a plain-language TV layout draft strategy without per-row technical notes', () => {
    expect(broadcastPlanSource).toContain("label: '电视播单'")
    expect(broadcastPlanSource).toContain('按草案里的栏目名找栏目或节目')
    expect(broadcastPlanSource).toContain('连续剧按播出顺序接着排')
    expect(broadcastPlanSource).toContain('找不到合适节目时留空，留给人工确认，不阻断编排')
    expect(broadcastPlanSource).toContain("const intent = playlistType.value === 'tv'")
    expect(broadcastPlanSource).toContain("? ''")
  })

  it('syncs successful runtime execution back from runtime or atomic state', () => {
    expect(chatPanelSource).toContain('const emitLatestRuntimeSchedule')
    expect(chatPanelSource).toContain('resolveScheduleItemsFromExecutionData(executionData)')
    expect(chatPanelSource).toContain('getAtomicCapabilities().getAllItems()')
    expect(chatPanelSource).toContain('emitLatestRuntimeSchedule(executed.data)')
    expect(chatPanelSource).toContain('emitLatestRuntimeSchedule(result.data)')
    expect(chatPanelSource).not.toContain('if (executionResult?.scheduleItems)')
  })

  it('captures pending summaries before cancelling bridge sessions', () => {
    const pendingCommandCancelBlock = chatPanelSource.match(/const cancelPendingCommand = async \(\) => \{[\s\S]*?\n\}/)?.[0] ?? ''
    const pendingAtomicCancelBlock = chatPanelSource.match(/const cancelPendingAtomicContext = async \(\) => \{[\s\S]*?\n\}/)?.[0] ?? ''

    expect(pendingCommandCancelBlock).toContain('const summary = pendingCommand.value.summary.replace')
    expect(pendingCommandCancelBlock.indexOf('const summary = pendingCommand.value.summary.replace')).toBeLessThan(
      pendingCommandCancelBlock.indexOf('pendingCommand.value = null'),
    )
    expect(pendingCommandCancelBlock).toContain('content: `${summary}，已取消执行。`')
    expect(pendingAtomicCancelBlock).toContain('const summary = formatPendingAtomicSummary(pendingAtomicContext.value).replace')
    expect(pendingAtomicCancelBlock.indexOf('const summary = formatPendingAtomicSummary(pendingAtomicContext.value).replace')).toBeLessThan(
      pendingAtomicCancelBlock.indexOf('pendingAtomicContext.value = null'),
    )
    expect(pendingAtomicCancelBlock).toContain('`${summary}，已取消更新草案。`')
    expect(pendingAtomicCancelBlock).toContain('`${summary}，已取消重新编排。`')
    expect(pendingAtomicCancelBlock).toContain('`${summary}，已取消当前补参。`')
    expect(pendingAtomicCancelBlock).toContain('我已停止这次草案更新建议，不会改动左侧草案或正式播单。')
    expect(pendingAtomicCancelBlock).toContain('我已停止这次正式重排，当前播单不会被改动。')
  })

  it('surfaces Agent Core audit summaries as first-class decision evidence', () => {
    expect(chatPanelSource).toContain('interface AgentAuditCard')
    expect(chatPanelSource).toContain('const getAgentAuditCards')
    expect(chatPanelSource).toContain('getMessageDetails(message)?.auditSummary')
    expect(chatPanelSource).toContain('class="agent-audit-panel"')
    expect(chatPanelSource).toContain('class="agent-audit-card"')
    expect(chatPanelSource).toContain('.agent-audit-card.is-blocker')
    expect(chatPanelSource).toContain('.agent-audit-card.is-warning')
  })

  it('keeps Agent Core search and LLM context budget in expandable decision evidence', () => {
    expect(chatPanelSource).toContain('interface AgentSearchSummaryCard')
    expect(chatPanelSource).toContain('const getAgentSearchSummaryCards')
    expect(chatPanelSource).toContain('class="agent-search-panel"')
    expect(chatPanelSource).toContain('查找记录')
    expect(chatPanelSource).not.toContain('class="agent-search-panel is-inline"')
    expect(chatPanelSource).toContain('class="agent-search-card"')
    expect(chatPanelSource).toContain('candidateSource?.query')
    expect(chatPanelSource).toContain('query?.facets')
    expect(chatPanelSource).toContain('candidateSource?.recordCount')
    expect(chatPanelSource).toContain('details.agentEvidenceBudget')
    expect(chatPanelSource).toContain('getBudgetLine(\'候选证据\'')
    expect(chatPanelSource).toContain('已精简显示')
  })

  it('surfaces Agent Core pending LLM context inside pending atomic panels', () => {
    expect(chatPanelSource).toContain("import { buildPendingLlmContext } from '@/services/agent/agentSession'")
    expect(chatPanelSource).toContain('const getPendingAtomicContextDetailItems')
    expect(chatPanelSource).toContain('agentPendingLlmContext: buildPendingLlmContext(agentPendingTask')
    expect(chatPanelSource).toContain('pending-agent-context-list')
    expect(chatPanelSource).toContain('{{ item.label }}')
    expect(chatPanelSource).toContain('{{ item.value }}')
  })

  it('builds runtime history from visible conversation only', () => {
    expect(chatPanelSource).toContain('const buildVisibleRuntimeHistory')
    expect(chatPanelSource).toContain('visibleMessages.value')
    expect(chatPanelSource).toContain('const currentWorkspaceKey = resolveCurrentPendingWorkspaceKey()')
    expect(chatPanelSource).toContain('buildWorkspaceScopedRuntimeHistory(visibleMessages.value')
    expect(chatPanelSource).toContain('const buildUserMessage = (content: string): Message =>')
    expect(chatPanelSource).toContain('workspaceKey: resolveCurrentMessageWorkspaceKey()')
    expect(chatPanelSource).toContain('history: buildVisibleRuntimeHistory(effectiveContent)')
    expect(chatPanelSource).not.toContain('history: messages.value.slice(-6).map((message) => message.content)')
  })

  it('expires pending review state before routing an unrelated foreground message', () => {
    expect(chatPanelSource).toContain('resolvePendingReviewLifecycle')
    expect(chatPanelSource).toContain('const currentWorkspaceKey = resolveCurrentPendingWorkspaceKey()')
    expect(chatPanelSource).toContain('const pendingReviewLifecycle = resolvePendingReviewLifecycle')
    expect(chatPanelSource).toContain('pendingWorkspaceKey: pendingReviewWorkspaceKey.value')
    expect(chatPanelSource).toContain('const usablePendingAtomicContext = pendingReviewLifecycle.canUsePendingReview ? pendingAtomicContext.value : null')
    expect(chatPanelSource).toContain('if (pendingReviewLifecycle.shouldExpire)')
    expect(chatPanelSource).toContain('pendingCommand.value = null')
    expect(chatPanelSource).toContain('pendingAtomicContext.value = null')
    expect(chatPanelSource).toContain('pendingReviewWorkspaceKey.value = null')
    expect(chatPanelSource).toContain('pendingCommand: usablePendingCommand')
    expect(chatPanelSource).toContain('pendingAtomicContext: usablePendingAtomicContext')
  })

  it('routes the next user turn as layout draft continuation after a partial draft prompt', () => {
    expect(chatPanelSource).toContain('const preferLayoutDraftContinuation = ref(false)')
    expect(chatPanelSource).toContain('const rememberLayoutDraftContinuationIfNeeded = (feedback: RuntimeFeedback) =>')
    expect(chatPanelSource).toContain("feedback.processTypeLabel !== '还要补草案'")
    expect(chatPanelSource).toContain("draftCompleteness?.status !== 'partial'")
    expect(chatPanelSource).toContain('preferLayoutDraftContinuation.value = true')
    expect(chatPanelSource).toContain('const preferLayoutDraftRefine = foregroundLayoutDraftRuntimeEnabled')
    expect(chatPanelSource).toContain('&& preferLayoutDraftContinuation.value')
    expect(chatPanelSource).toContain('preferLayoutDraftContinuation.value = false')
    expect(chatPanelSource).toContain('preferLayoutDraftRefine,')
  })

  it('interrupts stale pending review state before sending a new foreground message to runtime', () => {
    const sendMessageBlock = chatPanelSource.match(/const sendMessage = async \(\) => \{[\s\S]*?\n\}/)?.[0] ?? ''
    const interruptIndex = sendMessageBlock.indexOf('interruptPendingReviewForNewInput(content)')
    const userMessageIndex = sendMessageBlock.indexOf('messages.value.push(buildUserMessage(content))')
    const processIndex = sendMessageBlock.indexOf('await processMessage(content)')

    expect(sendMessageBlock).toContain('interruptPendingReviewForNewInput(content)')
    expect(interruptIndex).toBeGreaterThanOrEqual(0)
    expect(userMessageIndex).toBeGreaterThan(interruptIndex)
    expect(processIndex).toBeGreaterThan(userMessageIndex)
    expect(chatPanelSource).toContain("pendingReviewInterruptedNotice.value = resolvePendingReviewExpiredNotice('next_non_answer')")
    expect(chatPanelSource).toContain('const pendingReviewExpiredNotice = interruptedPendingReviewNotice ?? (pendingReviewLifecycle.shouldExpire')
    expect(chatPanelSource).toContain('await applyRuntimeDecision(decision, pendingReviewExpiredNotice)')
  })

  it('binds foreground pending review actions to the active playlist workspace', () => {
    expect(chatPanelSource).toContain('const pendingReviewWorkspaceKey = ref<string | null>(null)')
    expect(chatPanelSource).toContain('const resolveCurrentPendingWorkspaceKey = () => resolveForegroundWorkspaceKey')
    expect(chatPanelSource).toContain('const bindPendingReviewToCurrentWorkspace = () =>')
    expect(chatPanelSource).toContain('const isPendingReviewWorkspaceCurrent = () =>')
    expect(chatPanelSource).toContain('const expirePendingReviewForWorkspaceChange = (message: string) =>')
    expect(chatPanelSource).toContain('bindPendingReviewToCurrentWorkspace()')
    expect(chatPanelSource).toContain('if (!isPendingReviewWorkspaceCurrent())')
    expect(chatPanelSource).toContain('当前待确认操作不属于这个工作区，已失效')
    expect(chatPanelSource).toContain('pendingReviewWorkspaceKey.value = null')
  })

  it('interrupts a running orchestration and routes the typed message as the next foreground task', () => {
    const primaryActionBlock = chatPanelSource.match(/const handlePrimaryAction = async \(\) => \{[\s\S]*?\n\}/)?.[0] ?? ''
    const orchestrationWatchBlock = chatPanelSource.match(/watch\(\n  \(\) => \(\{\n    isOrchestrating:[\s\S]*?\{ immediate: true \},\n\)/)?.[0] ?? ''

    expect(chatPanelSource).toContain('const interruptedCommandAfterCancel = ref<string | null>(null)')
    expect(chatPanelSource).toContain('const terminalOrchestrationStatuses = new Set')
    expect(chatPanelSource).toContain('const isForegroundOrchestrationRunning = computed')
    expect(chatPanelSource).toContain("&& !isTerminalOrchestrationStatus(props.orchestrationSession?.status)")
    expect(chatPanelSource).toContain(":class=\"{ 'is-stop': isForegroundOrchestrationRunning }\"")
    expect(chatPanelSource).toContain("v-if=\"isForegroundOrchestrationRunning\"")
    expect(primaryActionBlock).toContain('if (isForegroundOrchestrationRunning.value)')
    expect(primaryActionBlock).toContain('const content = inputMessage.value.trim()')
    expect(primaryActionBlock).toContain('interruptedCommandAfterCancel.value = content')
    expect(primaryActionBlock).toContain('messages.value.push(buildUserMessage(content))')
    expect(primaryActionBlock).toContain("emit('cancelRequested')")
    expect(orchestrationWatchBlock).toContain('isOrchestrating: isForegroundOrchestrationRunning.value')
    expect(orchestrationWatchBlock).toContain('!isOrchestrating && interruptedCommandAfterCancel.value && !loading.value')
    expect(orchestrationWatchBlock).toContain("void processMessage(nextContent, '重新判断中')")
    expect(orchestrationWatchBlock).not.toContain('isOrchestrating ||\n      !sessionId')
  })

  it('renders foreground confirmation controls for Agent Core pending writes', () => {
    expect(chatPanelSource).toContain('showAgentPendingConfirmationPanel')
    expect(chatPanelSource).toContain('class="pending-command-panel agent-confirmation-panel"')
    expect(chatPanelSource).toContain('待确认执行')
    expect(chatPanelSource).toContain('confirmPendingAgentTask')
    expect(chatPanelSource).toContain('rejectPendingAgentTask')
    expect(chatPanelSource).toContain('formatPendingConfirmationPrimaryAction(pendingAtomicContext)')
    expect(chatPanelSource).toContain("isDraftResearchConfirmationContext(context)")
    expect(chatPanelSource).toContain("isFormalRebuildConfirmationContext(context)")
    expect(chatPanelSource).toContain("'确认重新编排'")
    expect(chatPanelSource).toContain("await processMessage('更新到草案', '更新草案中')")
    expect(chatPanelSource).toContain("await processMessage('确认重新编排', '重新编排中')")
    expect(chatPanelSource).toContain('await processMessage(content, progressLabel)')
    expect(chatPanelSource).toContain(':disabled="loading" @click="confirmPendingAgentTask"')
    expect(chatPanelSource).toContain(':disabled="loading" @click="rejectPendingAgentTask"')
    expect(chatPanelSource).toContain('formatPendingAtomicSummary(pendingAtomicContext)')
    expect(chatPanelSource).toContain('formatPendingAtomicConfirmationNote(pendingAtomicContext)')
    expect(chatPanelSource).toContain("context?.phase === 'draft_research_confirmation'")
    expect(chatPanelSource).toContain("context?.phase === 'formal_rebuild_confirmation'")
    expect(chatPanelSource).toContain('isDraftResearchConfirmationContext(pendingAtomicContext.value)')
    expect(chatPanelSource).toContain('isFormalRebuildConfirmationContext(pendingAtomicContext.value)')
  })

  it('keeps Agent Core as the continuation path for pending card selections', () => {
    const targetSelectionBlock = chatPanelSource.match(/const confirmPendingTargetSelection = async \(\) => \{[\s\S]*?const confirmPendingInsertRecommendation/)?.[0] ?? ''
    const insertRecommendationBlock = chatPanelSource.match(/const confirmPendingInsertRecommendation = async \(\) => \{[\s\S]*?const continuePendingAgentTask/)?.[0] ?? ''

    expect(chatPanelSource).toContain('const patchPendingAgentTaskSelection')
    expect(chatPanelSource).toContain("slot: 'targetItemId'")
    expect(chatPanelSource).toContain("slot: 'candidateId'")
    expect(chatPanelSource).toContain("source: selection.slot === 'candidateId' ? 'candidate_selection' as const : 'user_followup' as const")
    expect(chatPanelSource).toContain('missingSlots: pendingTask.missingSlots.filter')
    expect(chatPanelSource).toContain("phase: 'needs_confirmation' as const")
    expect(chatPanelSource).toContain("allowedActions: ['confirm', 'reject', 'start_new_task', 'cancel_pending']")

    expect(targetSelectionBlock).toContain('pendingAtomicContext.value.agentPendingTask')
    expect(targetSelectionBlock).toContain("slot: 'targetItemId'")
    expect(targetSelectionBlock).toContain("await continuePendingAgentTask('确认', '确认目标中')")
    expect(targetSelectionBlock.indexOf("await continuePendingAgentTask('确认', '确认目标中')")).toBeLessThan(
      targetSelectionBlock.indexOf('rehydratePendingTargetSelectionFromAtomicContext'),
    )
    expect(targetSelectionBlock).toContain('runtimeFacade.resolvePendingTargetSelection')

    expect(insertRecommendationBlock).toContain('pendingAtomicContext.value.agentPendingTask')
    expect(insertRecommendationBlock).toContain("slot: 'candidateId'")
    expect(insertRecommendationBlock).toContain("await continuePendingAgentTask('确认', `确认${actionLabel}中`)")
    expect(insertRecommendationBlock.indexOf("await continuePendingAgentTask('确认', `确认${actionLabel}中`)")).toBeLessThan(
      insertRecommendationBlock.indexOf('rehydratePendingInsertRecommendationFromAtomicContext'),
    )
    expect(insertRecommendationBlock).toContain('runtimeFacade.resolvePendingInsertRecommendation')
  })

  it('keeps foreground pending interactions limited to actionable cards', () => {
    expect(chatPanelSource).toContain('const formatPendingAgentTaskState')
    expect(chatPanelSource).toContain('const formatPendingAtomicGuidance')
    expect(chatPanelSource).toContain('const formatPendingAtomicKnownFacts')
    expect(chatPanelSource).toContain('const formatPendingAtomicConfirmationNote')
    expect(chatPanelSource).toContain('context.confirmationNote || context.reasoning')
    expect(chatPanelSource).toContain('const showClarifyingAtomicPanel = computed(() => false)')
    expect(chatPanelSource).not.toContain('showClarifyingAtomicPanel && pendingAtomicContext')
    expect(chatPanelSource).not.toContain('class="pending-command-panel clarifying-panel"')
    expect(chatPanelSource).toContain('class="pending-command-panel agent-confirmation-panel"')
    expect(chatPanelSource).toContain('class="playlist-file-card"')
    expect(chatPanelSource).toContain('class="pending-command-panel insert-recommendation-panel"')
    expect(chatPanelSource).toContain('showTargetSelectionAtomicPanel')
    expect(chatPanelSource).toContain('const getPendingAtomicClarificationSuggestions')
    expect(chatPanelSource).toContain("{ label: '9点', prompt: '9点' }")
    expect(chatPanelSource).toContain("{ label: '10点', prompt: '10点' }")
    expect(chatPanelSource).toContain('const continuePendingAtomicClarification')
    expect(chatPanelSource).toContain('void sendMessage()')
    expect(chatPanelSource).toContain('我已经识别到要插入')
    expect(chatPanelSource).toContain('还需要你告诉我放到哪个播出位置')
    expect(chatPanelSource).toContain('已预演，等待确认写入')
    expect(chatPanelSource).toContain("push('处理状态', formatPendingAgentTaskState(pendingTask.phase))")
    expect(chatPanelSource).not.toContain("push('上下文状态', `${pendingTask.intent} · ${pendingTask.phase}`)")
    expect(chatPanelSource).not.toContain('动作：{{ formatAtomicActionLabel')
    expect(chatPanelSource).not.toContain('缺少：{{ formatAtomicMissingFieldLabel')
    expect(chatPanelSource).toContain('已定位：${targetPart}')
    expect(chatPanelSource).toContain('确认后删除，取消则不改动播单')
    expect(chatPanelSource).toContain(':disabled="loading || !pendingAtomicTargetSelectedItemId"')
    expect(chatPanelSource).toContain(':disabled="loading || !pendingAtomicInsertSelectedCandidateId"')
  })

  it('keeps pending task and recommendation panels in editor-facing language', () => {
    expect(chatPanelSource).toContain('formatCompositeTaskSummary(context.compositeTaskRun)')
    expect(chatPanelSource).toContain('const formatCompositeTaskConfirmationNote')
    expect(chatPanelSource).toContain('formatRecommendationStrengthLabel(index)')
    expect(chatPanelSource).toContain('我按节目线索和当前播单排好了候选')
    expect(chatPanelSource).toContain('选好后我会先预演插入，确认没有问题再写入。')
    expect(chatPanelSource).not.toContain('置信度 {{ Math.round(candidate.confidence * 100) }}%')
    expect(chatPanelSource).not.toContain('相似候选已经按匹配度排序')
    expect(chatPanelSource).not.toContain('待确认任务：${context.compositeTaskRun.goal}')
    expect(chatPanelSource).not.toContain('我会按步骤处理：${stageText}')
    expect(chatPanelSource).not.toContain('匹配度 ${confidenceText}')
  })

  it('clears stale pending Agent context when a new foreground runtime message resolves', () => {
    const messageDecisionBlock = chatPanelSource.match(/case 'message':[\s\S]*?return/)?.[0] ?? ''

    expect(messageDecisionBlock).toContain('appendRuntimeFeedback(withRuntimeFeedbackNotice(decision.feedback, leadingNotice))')
    expect(messageDecisionBlock).toContain('pendingAtomicContext.value = decision.pendingAtomicClarification')
    expect(messageDecisionBlock).toContain(': null')
  })

  it('clears stale pending tasks when the active playlist document changes', () => {
    expect(broadcastPlanSource).toContain(':playlist-id="currentPlaylistId"')
    expect(chatPanelSource).toContain('playlistId?: string | null')
    expect(chatPanelSource).toContain('watch(() => props.playlistId')
    expect(chatPanelSource).toContain('resolveForegroundWorkspaceTransition')
    expect(chatPanelSource).toContain('playlistContextTransition.clearLayoutDraft')
    expect(chatPanelSource).toContain('const clearPendingRuntimeTaskState')
    expect(chatPanelSource).toContain('pendingCommand.value = null')
    expect(chatPanelSource).toContain('pendingAtomicContext.value = null')
    expect(chatPanelSource).toContain('transition.changed')
  })

  it('treats pending review like a one-turn Codex review gate in the foreground input path', () => {
    expect(chatPanelSource).toContain('const pendingReviewLifecycle = resolvePendingReviewLifecycle')
    expect(chatPanelSource).toContain('const usablePendingCommand = pendingReviewLifecycle.canUsePendingReview ? pendingCommand.value : null')
    expect(chatPanelSource).toContain('const usablePendingAtomicContext = pendingReviewLifecycle.canUsePendingReview ? pendingAtomicContext.value : null')
    expect(chatPanelSource).toContain('if (usablePendingCommand && isPendingReviewCancelText(content))')
    expect(chatPanelSource).toContain('if (usablePendingCommand && isPendingReviewConfirmText(content))')
    expect(chatPanelSource).toContain('runtimeFacade.executePendingCommand({')
    expect(chatPanelSource).toContain('const pendingReviewInterruptedNotice = ref<string | null>(null)')
    expect(chatPanelSource).toContain('const interruptPendingReviewForNewInput = (content: string): boolean =>')
    expect(chatPanelSource).toContain('interruptPendingReviewForNewInput(content)')
    expect(chatPanelSource).toContain('const interruptedPendingReviewNotice = pendingReviewInterruptedNotice.value')
    expect(chatPanelSource).toContain('const pendingReviewExpiredNotice = interruptedPendingReviewNotice ?? (pendingReviewLifecycle.shouldExpire')
    expect(chatPanelSource).toContain('resolvePendingReviewExpiredNotice(pendingReviewLifecycle.expireReason)')
    expect(chatPanelSource).toContain('withRuntimeFeedbackNotice(decision.feedback, leadingNotice)')
    expect(chatPanelSource).toContain('await applyRuntimeDecision(decision, pendingReviewExpiredNotice)')
    expect(chatPanelSource).not.toContain('pushPendingReviewExpiredMessage(pendingReviewLifecycle.expireReason)')
  })

  it('keeps recoverable LLM failure retry in the foreground message path', () => {
    expect(chatPanelSource).toContain('const recoverableRuntimeFailure = ref<RecoverableRuntimeFailure | null>(null)')
    expect(chatPanelSource).toContain('const isRecoverableRuntimeRetryText = (content: string): boolean =>')
    expect(chatPanelSource).toContain('const resolveRecoverableRuntimeRetryInput = (content: string): string | null | undefined =>')
    expect(chatPanelSource).toContain('const extractRecoverableRuntimeFailure = (')
    expect(chatPanelSource).toContain('details?.llmFailure')
    expect(chatPanelSource).toContain('recoverableUserInput')
    expect(chatPanelSource).toContain('effectiveContent = retryInput')
    expect(chatPanelSource).toContain('这次模型没有正常返回，我还没有修改草案或播单。你可以直接说“重试”')
  })
})
